namespace Esp
{
    public enum CodeId
    {
        Nothing,
        UpdateAuditMonitor,
        BindWithModule,
        BindWithScanF,
        UnBindWithScanF,
        BindWithMainF,
        UnBindWithMainF,
        BindwithScan,
        DisposeModule,
        UpdateLblDirectories,
        UpdateLblDirFiles,
        UpdateLblCurFile,
        RunScanForm,
        ProgresBarStep,
        ProgresBarMax,
        PauseScan,
        StopScan,
        AddToAuditResult,
        ListReportAudit,
        TestHookKeyboard,
        TestHookClipboard,
        TestHookMouse,
        TestHookApp,
        TestHookPrint,
        TestCameraSpy
    }
}
